//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GAMELOCK_project.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string username {
            get {
                return ((string)(this["username"]));
            }
            set {
                this["username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string hasopenedonce {
            get {
                return ((string)(this["hasopenedonce"]));
            }
            set {
                this["hasopenedonce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string mondaystarttime {
            get {
                return ((string)(this["mondaystarttime"]));
            }
            set {
                this["mondaystarttime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string mondayendtime {
            get {
                return ((string)(this["mondayendtime"]));
            }
            set {
                this["mondayendtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string mondaystarttime1 {
            get {
                return ((string)(this["mondaystarttime1"]));
            }
            set {
                this["mondaystarttime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string mondayendtime1 {
            get {
                return ((string)(this["mondayendtime1"]));
            }
            set {
                this["mondayendtime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string mondaystarttime2 {
            get {
                return ((string)(this["mondaystarttime2"]));
            }
            set {
                this["mondaystarttime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string mondayendtime2 {
            get {
                return ((string)(this["mondayendtime2"]));
            }
            set {
                this["mondayendtime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string tuesdaystarttime {
            get {
                return ((string)(this["tuesdaystarttime"]));
            }
            set {
                this["tuesdaystarttime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string tuesdayendtime {
            get {
                return ((string)(this["tuesdayendtime"]));
            }
            set {
                this["tuesdayendtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string tuesdaystarttime1 {
            get {
                return ((string)(this["tuesdaystarttime1"]));
            }
            set {
                this["tuesdaystarttime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string tuesdayendtime1 {
            get {
                return ((string)(this["tuesdayendtime1"]));
            }
            set {
                this["tuesdayendtime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string tuesdaystarttime2 {
            get {
                return ((string)(this["tuesdaystarttime2"]));
            }
            set {
                this["tuesdaystarttime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string tuesdayendtime2 {
            get {
                return ((string)(this["tuesdayendtime2"]));
            }
            set {
                this["tuesdayendtime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string wednesdaystarttime {
            get {
                return ((string)(this["wednesdaystarttime"]));
            }
            set {
                this["wednesdaystarttime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string wednesdayendtime {
            get {
                return ((string)(this["wednesdayendtime"]));
            }
            set {
                this["wednesdayendtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string wednesdaystarttime1 {
            get {
                return ((string)(this["wednesdaystarttime1"]));
            }
            set {
                this["wednesdaystarttime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string wednesdayendtime1 {
            get {
                return ((string)(this["wednesdayendtime1"]));
            }
            set {
                this["wednesdayendtime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string wednesdaystarttime2 {
            get {
                return ((string)(this["wednesdaystarttime2"]));
            }
            set {
                this["wednesdaystarttime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string wednesdayendtime2 {
            get {
                return ((string)(this["wednesdayendtime2"]));
            }
            set {
                this["wednesdayendtime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string thursdaystarttime {
            get {
                return ((string)(this["thursdaystarttime"]));
            }
            set {
                this["thursdaystarttime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string thursdayendtime {
            get {
                return ((string)(this["thursdayendtime"]));
            }
            set {
                this["thursdayendtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string thursdaystarttime1 {
            get {
                return ((string)(this["thursdaystarttime1"]));
            }
            set {
                this["thursdaystarttime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string thursdayendtime1 {
            get {
                return ((string)(this["thursdayendtime1"]));
            }
            set {
                this["thursdayendtime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string thursdaystarttime2 {
            get {
                return ((string)(this["thursdaystarttime2"]));
            }
            set {
                this["thursdaystarttime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string thursdayendtime2 {
            get {
                return ((string)(this["thursdayendtime2"]));
            }
            set {
                this["thursdayendtime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string edittimeswindow {
            get {
                return ((string)(this["edittimeswindow"]));
            }
            set {
                this["edittimeswindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string fridaystarttime {
            get {
                return ((string)(this["fridaystarttime"]));
            }
            set {
                this["fridaystarttime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string fridayendtime {
            get {
                return ((string)(this["fridayendtime"]));
            }
            set {
                this["fridayendtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string fridaystarttime1 {
            get {
                return ((string)(this["fridaystarttime1"]));
            }
            set {
                this["fridaystarttime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string fridayendtime1 {
            get {
                return ((string)(this["fridayendtime1"]));
            }
            set {
                this["fridayendtime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string fridaystarttime2 {
            get {
                return ((string)(this["fridaystarttime2"]));
            }
            set {
                this["fridaystarttime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string fridayendtime2 {
            get {
                return ((string)(this["fridayendtime2"]));
            }
            set {
                this["fridayendtime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string saturdaystarttime {
            get {
                return ((string)(this["saturdaystarttime"]));
            }
            set {
                this["saturdaystarttime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string saturdayendtime {
            get {
                return ((string)(this["saturdayendtime"]));
            }
            set {
                this["saturdayendtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string saturdaystarttime1 {
            get {
                return ((string)(this["saturdaystarttime1"]));
            }
            set {
                this["saturdaystarttime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string saturdayendtime1 {
            get {
                return ((string)(this["saturdayendtime1"]));
            }
            set {
                this["saturdayendtime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string saturdaystarttime2 {
            get {
                return ((string)(this["saturdaystarttime2"]));
            }
            set {
                this["saturdaystarttime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string saturdayendtime2 {
            get {
                return ((string)(this["saturdayendtime2"]));
            }
            set {
                this["saturdayendtime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string sundaystarttime {
            get {
                return ((string)(this["sundaystarttime"]));
            }
            set {
                this["sundaystarttime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string sundayendtime {
            get {
                return ((string)(this["sundayendtime"]));
            }
            set {
                this["sundayendtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string sundaystarttime1 {
            get {
                return ((string)(this["sundaystarttime1"]));
            }
            set {
                this["sundaystarttime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string sundayendtime1 {
            get {
                return ((string)(this["sundayendtime1"]));
            }
            set {
                this["sundayendtime1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string sundaystarttime2 {
            get {
                return ((string)(this["sundaystarttime2"]));
            }
            set {
                this["sundaystarttime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string sundayendtime2 {
            get {
                return ((string)(this["sundayendtime2"]));
            }
            set {
                this["sundayendtime2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string mondaydelete {
            get {
                return ((string)(this["mondaydelete"]));
            }
            set {
                this["mondaydelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string tuesdaydelete {
            get {
                return ((string)(this["tuesdaydelete"]));
            }
            set {
                this["tuesdaydelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string wednesdaydelete {
            get {
                return ((string)(this["wednesdaydelete"]));
            }
            set {
                this["wednesdaydelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string thursdaydelete {
            get {
                return ((string)(this["thursdaydelete"]));
            }
            set {
                this["thursdaydelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("null")]
        public string fridaydelete {
            get {
                return ((string)(this["fridaydelete"]));
            }
            set {
                this["fridaydelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string mondaydelete1 {
            get {
                return ((string)(this["mondaydelete1"]));
            }
            set {
                this["mondaydelete1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string tuesdaydelete1 {
            get {
                return ((string)(this["tuesdaydelete1"]));
            }
            set {
                this["tuesdaydelete1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string wednesdaydelete1 {
            get {
                return ((string)(this["wednesdaydelete1"]));
            }
            set {
                this["wednesdaydelete1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string thursdaydelete1 {
            get {
                return ((string)(this["thursdaydelete1"]));
            }
            set {
                this["thursdaydelete1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string fridaydelete1 {
            get {
                return ((string)(this["fridaydelete1"]));
            }
            set {
                this["fridaydelete1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string saturdaydelete1 {
            get {
                return ((string)(this["saturdaydelete1"]));
            }
            set {
                this["saturdaydelete1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string sundaydelete1 {
            get {
                return ((string)(this["sundaydelete1"]));
            }
            set {
                this["sundaydelete1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string sundaydelete {
            get {
                return ((string)(this["sundaydelete"]));
            }
            set {
                this["sundaydelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string saturdaydelete {
            get {
                return ((string)(this["saturdaydelete"]));
            }
            set {
                this["saturdaydelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string mondaydelete2 {
            get {
                return ((string)(this["mondaydelete2"]));
            }
            set {
                this["mondaydelete2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string tuesdaydelete2 {
            get {
                return ((string)(this["tuesdaydelete2"]));
            }
            set {
                this["tuesdaydelete2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string wednesdaydelete2 {
            get {
                return ((string)(this["wednesdaydelete2"]));
            }
            set {
                this["wednesdaydelete2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string thursdaydelete2 {
            get {
                return ((string)(this["thursdaydelete2"]));
            }
            set {
                this["thursdaydelete2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string fridaydelete2 {
            get {
                return ((string)(this["fridaydelete2"]));
            }
            set {
                this["fridaydelete2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string saturdaydelete2 {
            get {
                return ((string)(this["saturdaydelete2"]));
            }
            set {
                this["saturdaydelete2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string sundaydelete2 {
            get {
                return ((string)(this["sundaydelete2"]));
            }
            set {
                this["sundaydelete2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string mondayselected {
            get {
                return ((string)(this["mondayselected"]));
            }
            set {
                this["mondayselected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string tuesdayselected {
            get {
                return ((string)(this["tuesdayselected"]));
            }
            set {
                this["tuesdayselected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string wednesdayselected {
            get {
                return ((string)(this["wednesdayselected"]));
            }
            set {
                this["wednesdayselected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string thursdayselected {
            get {
                return ((string)(this["thursdayselected"]));
            }
            set {
                this["thursdayselected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string fridayselected {
            get {
                return ((string)(this["fridayselected"]));
            }
            set {
                this["fridayselected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string saturdayselected {
            get {
                return ((string)(this["saturdayselected"]));
            }
            set {
                this["saturdayselected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string sundayselected {
            get {
                return ((string)(this["sundayselected"]));
            }
            set {
                this["sundayselected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string everydayselected {
            get {
                return ((string)(this["everydayselected"]));
            }
            set {
                this["everydayselected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string everydaydelete {
            get {
                return ((string)(this["everydaydelete"]));
            }
            set {
                this["everydaydelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string everydaydelete1 {
            get {
                return ((string)(this["everydaydelete1"]));
            }
            set {
                this["everydaydelete1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string everydaydelete2 {
            get {
                return ((string)(this["everydaydelete2"]));
            }
            set {
                this["everydaydelete2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string weekdayselected {
            get {
                return ((string)(this["weekdayselected"]));
            }
            set {
                this["weekdayselected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string weekdaydelete {
            get {
                return ((string)(this["weekdaydelete"]));
            }
            set {
                this["weekdaydelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string weekdaydelete1 {
            get {
                return ((string)(this["weekdaydelete1"]));
            }
            set {
                this["weekdaydelete1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string weekdaydelete2 {
            get {
                return ((string)(this["weekdaydelete2"]));
            }
            set {
                this["weekdaydelete2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string weekendselected {
            get {
                return ((string)(this["weekendselected"]));
            }
            set {
                this["weekendselected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string weekenddelete {
            get {
                return ((string)(this["weekenddelete"]));
            }
            set {
                this["weekenddelete"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string weekenddelete1 {
            get {
                return ((string)(this["weekenddelete1"]));
            }
            set {
                this["weekenddelete1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("closed")]
        public string weekenddelete2 {
            get {
                return ((string)(this["weekenddelete2"]));
            }
            set {
                this["weekenddelete2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string darkscheme {
            get {
                return ((string)(this["darkscheme"]));
            }
            set {
                this["darkscheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("no")]
        public string lightscheme {
            get {
                return ((string)(this["lightscheme"]));
            }
            set {
                this["lightscheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yes")]
        public string defaultscheme {
            get {
                return ((string)(this["defaultscheme"]));
            }
            set {
                this["defaultscheme"] = value;
            }
        }
    }
}
